export const REVENUE_BASE = "cohortRevenueD";
export const SESSION_BASE = "sessionD";
export const LTV_BASE = "ltvD";

// Retenten, Sigma Retention, Cohort Revenue = 1
// LTV, Cohort Roas = 2
export const PARTIAL_DAY_2 = 2;

export const COL_IDS = {
  name: "name",
  bid: "bid",
  budget: "budget",
  click: "click",
  impression: "impression",
  install: "install",
  nonOrganicInstall: "nonOrganicInstall",
  billableCost: "billableCost",
  billableInstall: "billableInstall",
  billableECpi: "billableECpi",

  arpdau: "arpdau",
  latestArpdau: "latestArpdau",
  dau: "dau",
  rev: "rev",
  lastestDau: "lastestDau",
  lastestRev: "lastestRev",
  ltvD1: "ltvD1",
  ltvD3: "ltvD3",
  ltvD7: "ltvD7",
  ltvD14: "ltvD14",
  ltvD30: "ltvD30",
  users: "users",

  retentionD1: "retentionD1",
  retentionD2: "retentionD2",
  retentionD3: "retentionD3",
  retentionD4: "retentionD4",
  retentionD5: "retentionD5",
  retentionD6: "retentionD6",
  retentionD7: "retentionD7",
  retentionD8: "retentionD8",
  retentionD9: "retentionD9",
  retentionD10: "retentionD10",
  retentionD11: "retentionD11",
  retentionD12: "retentionD12",
  retentionD13: "retentionD13",
  retentionD14: "retentionD14",
  retentionD15: "retentionD15",
  retentionD16: "retentionD16",
  retentionD17: "retentionD17",
  retentionD18: "retentionD18",
  retentionD19: "retentionD19",
  retentionD20: "retentionD20",
  retentionD21: "retentionD21",
  retentionD22: "retentionD22",
  retentionD23: "retentionD23",
  retentionD24: "retentionD24",
  retentionD25: "retentionD25",
  retentionD26: "retentionD26",
  retentionD27: "retentionD27",
  retentionD28: "retentionD28",
  retentionD29: "retentionD29",
  retentionD30: "retentionD30",

  retentionZD1: "retentionZD1",
  retentionZD2: "retentionZD2",
  retentionZD3: "retentionZD3",
  retentionZD4: "retentionZD4",
  retentionZD5: "retentionZD5",
  retentionZD6: "retentionZD6",
  retentionZD7: "retentionZD7",
  retentionZD8: "retentionZD8",
  retentionZD9: "retentionZD9",
  retentionZD10: "retentionZD10",
  retentionZD11: "retentionZD11",
  retentionZD12: "retentionZD12",
  retentionZD13: "retentionZD13",
  retentionZD14: "retentionZD14",
  retentionZD15: "retentionZD15",
  retentionZD16: "retentionZD16",
  retentionZD17: "retentionZD17",
  retentionZD18: "retentionZD18",
  retentionZD19: "retentionZD19",
  retentionZD20: "retentionZD20",
  retentionZD21: "retentionZD21",
  retentionZD22: "retentionZD22",
  retentionZD23: "retentionZD23",
  retentionZD24: "retentionZD24",
  retentionZD25: "retentionZD25",
  retentionZD26: "retentionZD26",
  retentionZD27: "retentionZD27",
  retentionZD28: "retentionZD28",
  retentionZD29: "retentionZD29",
  retentionZD30: "retentionZD30",

  cost: "cost",
  ecpi: "ecpi",
  ctr: "ctr",
  cvr: "cvr",
  ecpc: "ecpc",
  ecpm: "ecpm",
  ocvr: "ocvr",
  skanCost: "skanCost",
  skanInstall: "skanInstall",
  skanECPI: "skanECPI",
  attributeRevenue: "attributeRevenue",
  attributeSession: "attributeSession",
  attributeClick: "attributeClick",
  attributeCost: "attributeCost",
  attributeECpi: "attributeECpi",
  attributeImpression: "attributeImpression",
  attributeInstall: "attributeInstall",
  attributeRevenueAdEvent: "attributeRevenueAdEvent",
  attributeRevenuePurchaseEvent: "attributeRevenuePurchaseEvent",

  cohortCost: "cohortCost",
  cohortEcpi: "cohortEcpi",
  cohortRevenueD0: "cohortRevenueD0",
  cohortRevenueD1: "cohortRevenueD1",
  cohortRevenueD3: "cohortRevenueD3",
  cohortRevenueD7: "cohortRevenueD7",
  cohortRevenueD14: "cohortRevenueD14",
  cohortRevenueD30: "cohortRevenueD30",
  cohortRevenueD60: "cohortRevenueD60",
  cohortRevenueD90: "cohortRevenueD90",
  cohortRevenueD180: "cohortRevenueD180",
  cohortROASD0: "cohortROASD0",
  cohortROASD1: "cohortROASD1",
  cohortROASD3: "cohortROASD3",
  cohortROASD7: "cohortROASD7",
  cohortROASD14: "cohortROASD14",
  cohortROASD30: "cohortROASD30",
  cohortROASD60: "cohortROASD60",
  cohortROASD90: "cohortROASD90",
  cohortROASD180: "cohortROASD180",
  activityROI: "activityROI",
  // cohortROID0: "cohortROID0",
  // cohortROID1: "cohortROID1",
  // cohortROID3: "cohortROID3",
  // cohortROID7: "cohortROID7",
  // cohortROID14: "cohortROID14",
  // cohortROID30: "cohortROID30",
  // cohortROID60: "cohortROID60",
  // cohortROID90: "cohortROID90",
  // cohortROID180: "cohortROID180",
  // Các field bên dưới được dùng trong table của dashboard
  clickThroughInstall: "clickThroughInstall",
  viewThoughInstall: "viewThoughInstall",
  nullConversionRate: "nullConversionRate",
  clickToInstallRate: "clickToInstallRate",
  totalRevenueModel: "totalRevenueModel",
  totalRevenue: "totalRevenue",
  skanOrganicInstall: "skanOrganicInstall",
  skanNonOrganicInstall: "skanNonOrganicInstall",
};

export const WRAPPER_COL_IDS = {
  cohort: "cohort",
  revenueLv: "revenueLv",
  roasLv: "roasLv",
  roiLv: "roiLv",
  retentionLv: "retentionLv",
  cohortRevenue: "cohortRevenue",
  attrLv: "attrLv",
  skanLv: "skanLv",
  adNetworkLv: "adNetworkLv",
  skanOverviewLv: "skanOverviewLv", // Dashboard
  ltvLv: "ltvLv",
  // session: "session",
  retention: "retention",
  retentionz: "retentionz",
};

const cohortRevenueSetting = {
  title: "Cohort Revenue",
  key: WRAPPER_COL_IDS.cohortRevenue,
  fullName: true,
  children: [
    { title: "D0", key: COL_IDS.cohortRevenueD0 },
    { title: "D1", key: COL_IDS.cohortRevenueD1 },
    { title: "D3", key: COL_IDS.cohortRevenueD3 },
    { title: "D7", key: COL_IDS.cohortRevenueD7 },
    { title: "D14", key: COL_IDS.cohortRevenueD14 },
    { title: "D30", key: COL_IDS.cohortRevenueD30 },
    { title: "D60", key: COL_IDS.cohortRevenueD60 },
    { title: "D90", key: COL_IDS.cohortRevenueD90 },
    { title: "D180", key: COL_IDS.cohortRevenueD180 },
  ],
};

export const CohortSetting = {
  title: "Cohort",
  key: WRAPPER_COL_IDS.cohort,
  fullName: true,
  children: [
    { title: "Cost", key: COL_IDS.cohortCost },
    { title: "eCPI", key: COL_IDS.cohortEcpi },
    { title: "Installs", key: COL_IDS.users },
    {
      title: "Cohort ROAS",
      key: WRAPPER_COL_IDS.roasLv,
      fullName: true,
      children: [
        { title: "D0", key: COL_IDS.cohortROASD0 },
        { title: "D1", key: COL_IDS.cohortROASD1 },
        { title: "D3", key: COL_IDS.cohortROASD3 },
        { title: "D7", key: COL_IDS.cohortROASD7 },
        { title: "D14", key: COL_IDS.cohortROASD14 },
        { title: "D30", key: COL_IDS.cohortROASD30 },
        { title: "D60", key: COL_IDS.cohortROASD60 },
        { title: "D90", key: COL_IDS.cohortROASD90 },
        { title: "D180", key: COL_IDS.cohortROASD180 },
      ],
    },
    cohortRevenueSetting,
  ],
};
// Overview dùng CohortSetting2 do vẫn có Cohort ROI
export const CohortSetting2 = {
  title: "Cohort",
  key: WRAPPER_COL_IDS.cohort,
  fullName: true,
  children: [
    { title: "Cost", key: COL_IDS.cohortCost },
    {
      title: "Cohort ROAS",
      key: WRAPPER_COL_IDS.roasLv,
      fullName: true,
      children: [
        { title: "D0", key: COL_IDS.cohortROASD0 },
        { title: "D1", key: COL_IDS.cohortROASD1 },
        { title: "D3", key: COL_IDS.cohortROASD3 },
        { title: "D7", key: COL_IDS.cohortROASD7 },
        { title: "D14", key: COL_IDS.cohortROASD14 },
        { title: "D30", key: COL_IDS.cohortROASD30 },
        { title: "D60", key: COL_IDS.cohortROASD60 },
        { title: "D90", key: COL_IDS.cohortROASD90 },
        { title: "D180", key: COL_IDS.cohortROASD180 },
      ],
    },
    {
      title: "Cohort ROI",
      key: WRAPPER_COL_IDS.roiLv,
      fullName: true,
      children: [
        { title: "Activity ROI", key: COL_IDS.activityROI },
        // { title: "D0", key: COL_IDS.cohortROID0 },
        // { title: "D1", key: COL_IDS.cohortROID1 },
        // { title: "D3", key: COL_IDS.cohortROID3 },
        // { title: "D7", key: COL_IDS.cohortROID7 },
        // { title: "D14", key: COL_IDS.cohortROID14 },
        // { title: "D30", key: COL_IDS.cohortROID30 },
        // { title: "D60", key: COL_IDS.cohortROID60 },
        // { title: "D90", key: COL_IDS.cohortROID90 },
        // { title: "D180", key: COL_IDS.cohortROID180 },
      ],
    },
    cohortRevenueSetting,
  ],
};
export const RetentionSetting = {
  title: "Retention",
  key: WRAPPER_COL_IDS.retention,
  fullName: true,
  children: [
    { title: "Users", key: COL_IDS.users },
    { title: "Retention D1", key: COL_IDS.retentionD1 },
    { title: "Retention D2", key: COL_IDS.retentionD2 },
    { title: "Retention D3", key: COL_IDS.retentionD3 },
    { title: "Retention D4", key: COL_IDS.retentionD4 },
    { title: "Retention D5", key: COL_IDS.retentionD5 },
    { title: "Retention D6", key: COL_IDS.retentionD6 },
    { title: "Retention D7", key: COL_IDS.retentionD7 },
    { title: "Retention D8", key: COL_IDS.retentionD8 },
    { title: "Retention D9", key: COL_IDS.retentionD9 },
    { title: "Retention D10", key: COL_IDS.retentionD10 },
    { title: "Retention D11", key: COL_IDS.retentionD11 },
    { title: "Retention D12", key: COL_IDS.retentionD12 },
    { title: "Retention D13", key: COL_IDS.retentionD13 },
    { title: "Retention D14", key: COL_IDS.retentionD14 },
    { title: "Retention D15", key: COL_IDS.retentionD15 },
    { title: "Retention D16", key: COL_IDS.retentionD16 },
    { title: "Retention D17", key: COL_IDS.retentionD17 },
    { title: "Retention D18", key: COL_IDS.retentionD18 },
    { title: "Retention D19", key: COL_IDS.retentionD19 },
    { title: "Retention D20", key: COL_IDS.retentionD20 },
    { title: "Retention D21", key: COL_IDS.retentionD21 },
    { title: "Retention D22", key: COL_IDS.retentionD22 },
    { title: "Retention D23", key: COL_IDS.retentionD23 },
    { title: "Retention D24", key: COL_IDS.retentionD24 },
    { title: "Retention D25", key: COL_IDS.retentionD25 },
    { title: "Retention D26", key: COL_IDS.retentionD26 },
    { title: "Retention D27", key: COL_IDS.retentionD27 },
    { title: "Retention D28", key: COL_IDS.retentionD28 },
    { title: "Retention D29", key: COL_IDS.retentionD29 },
    { title: "Retention D30", key: COL_IDS.retentionD30 },
  ],
};
export const SigmaRetentionSetting = {
  title: "Sigma Retention",
  key: WRAPPER_COL_IDS.retentionz,
  fullName: true,
  children: [
    { title: "Σ RR D1", key: COL_IDS.retentionZD1 },
    { title: "Σ RR D2", key: COL_IDS.retentionZD2 },
    { title: "Σ RR D3", key: COL_IDS.retentionZD3 },
    { title: "Σ RR D4", key: COL_IDS.retentionZD4 },
    { title: "Σ RR D5", key: COL_IDS.retentionZD5 },
    { title: "Σ RR D6", key: COL_IDS.retentionZD6 },
    { title: "Σ RR D7", key: COL_IDS.retentionZD7 },
    { title: "Σ RR D8", key: COL_IDS.retentionZD8 },
    { title: "Σ RR D9", key: COL_IDS.retentionZD9 },
    { title: "Σ RR D10", key: COL_IDS.retentionZD10 },
    { title: "Σ RR D11", key: COL_IDS.retentionZD11 },
    { title: "Σ RR D12", key: COL_IDS.retentionZD12 },
    { title: "Σ RR D13", key: COL_IDS.retentionZD13 },
    { title: "Σ RR D14", key: COL_IDS.retentionZD14 },
    { title: "Σ RR D15", key: COL_IDS.retentionZD15 },
    { title: "Σ RR D16", key: COL_IDS.retentionZD16 },
    { title: "Σ RR D17", key: COL_IDS.retentionZD17 },
    { title: "Σ RR D18", key: COL_IDS.retentionZD18 },
    { title: "Σ RR D19", key: COL_IDS.retentionZD19 },
    { title: "Σ RR D20", key: COL_IDS.retentionZD20 },
    { title: "Σ RR D21", key: COL_IDS.retentionZD21 },
    { title: "Σ RR D22", key: COL_IDS.retentionZD22 },
    { title: "Σ RR D23", key: COL_IDS.retentionZD23 },
    { title: "Σ RR D24", key: COL_IDS.retentionZD24 },
    { title: "Σ RR D25", key: COL_IDS.retentionZD25 },
    { title: "Σ RR D26", key: COL_IDS.retentionZD26 },
    { title: "Σ RR D27", key: COL_IDS.retentionZD27 },
    { title: "Σ RR D28", key: COL_IDS.retentionZD28 },
    { title: "Σ RR D29", key: COL_IDS.retentionZD29 },
    { title: "Σ RR D30", key: COL_IDS.retentionZD30 },
  ],
};
const SessionObj = {
  // title: "Session",
  // key: WRAPPER_COL_IDS.session,
  // fullName: true,
  // children: [
  //   { title: "Session D1", key: COL_IDS.sessionD1 },
  //   { title: "Session D2", key: COL_IDS.sessionD2 },
  //   { title: "Session D3", key: COL_IDS.sessionD3 },
  //   { title: "Session D4", key: COL_IDS.sessionD4 },
  //   { title: "Session D5", key: COL_IDS.sessionD5 },
  //   { title: "Session D6", key: COL_IDS.sessionD6 },
  //   { title: "Session D7", key: COL_IDS.sessionD7 },
  //   { title: "Session D8", key: COL_IDS.sessionD8 },
  //   { title: "Session D9", key: COL_IDS.sessionD9 },
  //   { title: "Session D10", key: COL_IDS.sessionD10 },
  //   { title: "Session D11", key: COL_IDS.sessionD11 },
  //   { title: "Session D12", key: COL_IDS.sessionD12 },
  //   { title: "Session D13", key: COL_IDS.sessionD13 },
  //   { title: "Session D14", key: COL_IDS.sessionD14 },
  //   { title: "Session D15", key: COL_IDS.sessionD15 },
  //   { title: "Session D16", key: COL_IDS.sessionD16 },
  //   { title: "Session D17", key: COL_IDS.sessionD17 },
  //   { title: "Session D18", key: COL_IDS.sessionD18 },
  //   { title: "Session D19", key: COL_IDS.sessionD19 },
  //   { title: "Session D20", key: COL_IDS.sessionD20 },
  //   { title: "Session D21", key: COL_IDS.sessionD21 },
  //   { title: "Session D22", key: COL_IDS.sessionD22 },
  //   { title: "Session D23", key: COL_IDS.sessionD23 },
  //   { title: "Session D24", key: COL_IDS.sessionD24 },
  //   { title: "Session D25", key: COL_IDS.sessionD25 },
  //   { title: "Session D26", key: COL_IDS.sessionD26 },
  //   { title: "Session D27", key: COL_IDS.sessionD27 },
  //   { title: "Session D28", key: COL_IDS.sessionD28 },
  //   { title: "Session D29", key: COL_IDS.sessionD29 },
  //   { title: "Session D30", key: COL_IDS.sessionD30 },
  // ],
};

export const minifiedAdNetworkCols = [
  { title: "Cost", key: COL_IDS.cost },
  { title: "Installs", key: COL_IDS.install },
  { title: "eCPI", key: COL_IDS.ecpi },
  { title: "Impressions", key: COL_IDS.impression },
  { title: "Clicks", key: COL_IDS.click },
  { title: "CTR", key: COL_IDS.ctr },
  { title: "CVR", key: COL_IDS.cvr },
  { title: "eCPC", key: COL_IDS.ecpc },
  { title: "eCPM", key: COL_IDS.ecpm },
  { title: "oCVR", key: COL_IDS.ocvr },
];

export const TREE_COLS = [
  { title: "Name", key: COL_IDS.name },
  { title: "Bid", key: COL_IDS.bid },
  { title: "Daily Budget", key: COL_IDS.budget },
  {
    title: "Ad Network",
    key: WRAPPER_COL_IDS.adNetworkLv,
    children: [
      ...minifiedAdNetworkCols,
      { title: "Billable cost", key: COL_IDS.billableCost },
      { title: "Billable install", key: COL_IDS.billableInstall },
      { title: "Billable eCpi", key: COL_IDS.billableECpi },
    ],
  },
  {
    title: "LTV",
    key: WRAPPER_COL_IDS.ltvLv,
    fullName: true,
    children: [
      { title: "LTV D1", key: COL_IDS.ltvD1 },
      { title: "LTV D3", key: COL_IDS.ltvD3 },
      { title: "LTV D7", key: COL_IDS.ltvD7 },
      { title: "LTV D14", key: COL_IDS.ltvD14 },
      { title: "LTV D30", key: COL_IDS.ltvD30 },
    ],
  },
  CohortSetting,
  {
    title: "MMP metrics",
    key: WRAPPER_COL_IDS.attrLv,
    fullName: true,
    children: [
      { title: "Cost", key: COL_IDS.attributeCost },
      { title: "Installs", key: COL_IDS.attributeInstall },
      { title: "eCPI", key: COL_IDS.attributeECpi },
      {
        title: "Activity Revenue (af_ad_revenue)",
        key: COL_IDS.attributeRevenueAdEvent,
      },
      {
        title: "Activity Revenue (af_purchase)",
        key: COL_IDS.attributeRevenuePurchaseEvent,
      },
      { title: "LTV Revenue", key: COL_IDS.attributeRevenue },
      { title: "Session", key: COL_IDS.attributeSession },
    ],
  },
  {
    title: "SKAN",
    key: WRAPPER_COL_IDS.skanLv,
    fullName: true,
    children: [
      { title: "Cost", key: COL_IDS.skanCost },
      { title: "Installs", key: COL_IDS.skanInstall },
      { title: "eCPI", key: COL_IDS.skanECPI },
    ],
  },
  // RetentionSetting,
  // SigmaRetentionSetting,
];
